// IndexedDB utility for storing MusicXML scores locally

export interface StoredScore {
  id?: number; // Auto-generated by IndexedDB
  name: string;
  xmlContent: string;
  timestamp: number;
  fileSize: number;
  hasChords?: boolean; // Flag indicating if chords have been added
}

const DB_NAME = "ScoreDB";
const STORE_NAME = "scores";
const DB_VERSION = 1;

// Open or create the database
function openDB(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const request = indexedDB.open(DB_NAME, DB_VERSION);

    request.onerror = () => reject(request.error);
    request.onsuccess = () => resolve(request.result);

    request.onupgradeneeded = (event) => {
      const db = (event.target as IDBOpenDBRequest).result;
      if (!db.objectStoreNames.contains(STORE_NAME)) {
        const objectStore = db.createObjectStore(STORE_NAME, {
          keyPath: "id",
          autoIncrement: true,
        });
        objectStore.createIndex("name", "name", { unique: false });
        objectStore.createIndex("timestamp", "timestamp", { unique: false });
      }
    };
  });
}

// Save a score to IndexedDB
export async function saveScore(
  name: string,
  xmlContent: string,
): Promise<number> {
  const db = await openDB();
  return new Promise((resolve, reject) => {
    const transaction = db.transaction([STORE_NAME], "readwrite");
    const store = transaction.objectStore(STORE_NAME);

    const score: StoredScore = {
      name,
      xmlContent,
      timestamp: Date.now(),
      fileSize: new Blob([xmlContent]).size,
    };

    const request = store.add(score);

    request.onsuccess = () => resolve(request.result as number);
    request.onerror = () => reject(request.error);

    transaction.oncomplete = () => db.close();
  });
}

// Get all scores from IndexedDB
export async function getAllScores(): Promise<StoredScore[]> {
  const db = await openDB();
  return new Promise((resolve, reject) => {
    const transaction = db.transaction([STORE_NAME], "readonly");
    const store = transaction.objectStore(STORE_NAME);
    const request = store.getAll();

    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error);

    transaction.oncomplete = () => db.close();
  });
}

// Get a single score by ID
export async function getScore(id: number): Promise<StoredScore | null> {
  const db = await openDB();
  return new Promise((resolve, reject) => {
    const transaction = db.transaction([STORE_NAME], "readonly");
    const store = transaction.objectStore(STORE_NAME);
    const request = store.get(id);

    request.onsuccess = () => resolve(request.result || null);
    request.onerror = () => reject(request.error);

    transaction.oncomplete = () => db.close();
  });
}

// Delete a score by ID
export async function deleteScore(id: number): Promise<void> {
  const db = await openDB();
  return new Promise((resolve, reject) => {
    const transaction = db.transaction([STORE_NAME], "readwrite");
    const store = transaction.objectStore(STORE_NAME);
    const request = store.delete(id);

    request.onsuccess = () => resolve();
    request.onerror = () => reject(request.error);

    transaction.oncomplete = () => db.close();
  });
}

// Validate if content is a valid MusicXML file
export function isValidMusicXML(content: string): boolean {
  // Simple validation: check if it contains MusicXML markers
  const hasXMLDeclaration = content.trim().startsWith("<?xml");
  const hasMusicXMLTag =
    content.includes("<score-partwise") || content.includes("<score-timewise");
  return hasXMLDeclaration && hasMusicXMLTag;
}

// Update a score's XML content (for adding chords)
export async function updateScoreContent(
  id: number,
  xmlContent: string,
  hasChords: boolean = false,
): Promise<void> {
  const db = await openDB();
  return new Promise((resolve, reject) => {
    const transaction = db.transaction([STORE_NAME], "readwrite");
    const store = transaction.objectStore(STORE_NAME);

    // First get the existing score
    const getRequest = store.get(id);

    getRequest.onsuccess = () => {
      const existingScore = getRequest.result as StoredScore;
      if (!existingScore) {
        reject(new Error("Score not found"));
        return;
      }

      // Update the score
      const updatedScore: StoredScore = {
        ...existingScore,
        xmlContent,
        fileSize: new Blob([xmlContent]).size,
        hasChords,
      };

      const putRequest = store.put(updatedScore);
      putRequest.onsuccess = () => resolve();
      putRequest.onerror = () => reject(putRequest.error);
    };

    getRequest.onerror = () => reject(getRequest.error);
    transaction.oncomplete = () => db.close();
  });
}
