/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/images/3d/sushi_tekka.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" position={[0, -1.3, 0]} scale={7}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.getavox.geometry}
          material={materials["palette.003"]}
          position={[0, 0.07, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.22}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tekka.geometry}
          material={materials.tekka}
          position={[0, 0.11, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.04}
        />
      </group>
    </group>
  );
}
