/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/images/3d/alagin.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[0, 2.6, -0.62]}
        rotation={[-2.74, -0.22, 0]}
        scale={[1.29, 1.29, 1.29]}
      >
        <pointLight
          intensity={10}
          decay={2}
          color="#ff3317"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.alagin005.geometry}
        material={materials["palette.015"]}
        position={[-0.01, -0.8, 0.04]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.8}
      />
    </group>
  );
}

useGLTF.preload("/images/3d/alagin.glb");
