/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/images/3d/speaker.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="speaker_JBL"
          castShadow
          receiveShadow
          geometry={nodes.speaker_JBL.geometry}
          material={materials["palette.008"]}
          position={[-0.01, -2, 0.01]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={1.41}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/images/3d/speaker.glb");
