/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/images/3d/sushi_ikura.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" position={[0, -1.3, 0]} scale={1.4}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球001.geometry}
          material={nodes.球001.material}
          position={[0.06, 1.3, 0.35]}
          rotation={[-0.16, 0.1, -0.05]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球002.geometry}
          material={nodes.球002.material}
          position={[0.06, 1.33, 0.35]}
          rotation={[-0.16, 0.1, -0.05]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球003.geometry}
          material={nodes.球003.material}
          position={[0.17, 1.3, -0.01]}
          rotation={[-0.16, 0.1, -0.05]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球006.geometry}
          material={nodes.球006.material}
          position={[0.17, 1.34, -0.02]}
          rotation={[-0.16, 0.1, -0.05]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球007.geometry}
          material={nodes.球007.material}
          position={[0.22, 1.29, -0.2]}
          rotation={[-0.16, 0.1, -0.05]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球008.geometry}
          material={nodes.球008.material}
          position={[0.22, 1.33, -0.2]}
          rotation={[-0.16, 0.1, -0.05]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球009.geometry}
          material={nodes.球009.material}
          position={[0.08, 1.25, -0.29]}
          rotation={[-0.16, 0.1, -0.05]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球010.geometry}
          material={nodes.球010.material}
          position={[0.08, 1.28, -0.3]}
          rotation={[-0.16, 0.1, -0.05]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球011.geometry}
          material={nodes.球011.material}
          position={[0.07, 1.32, 0.16]}
          rotation={[0.32, 0.58, 0.37]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球012.geometry}
          material={nodes.球012.material}
          position={[0.05, 1.35, 0.18]}
          rotation={[0.32, 0.58, 0.37]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球013.geometry}
          material={nodes.球013.material}
          position={[0.25, 1.28, 0.35]}
          rotation={[-0.16, 0.1, -0.05]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球014.geometry}
          material={nodes.球014.material}
          position={[0.25, 1.32, 0.34]}
          rotation={[-0.16, 0.1, -0.05]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球015.geometry}
          material={nodes.球015.material}
          position={[0.35, 1.29, -0.01]}
          rotation={[-0.16, 0.1, -0.05]}
          scale={[0.08, 0.08, 0.08]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球016.geometry}
          material={nodes.球016.material}
          position={[0.35, 1.33, -0.02]}
          rotation={[-0.16, 0.1, -0.05]}
          scale={[0.04, 0.04, 0.04]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球017.geometry}
          material={nodes.球017.material}
          position={[0.41, 1.28, -0.2]}
          rotation={[-0.16, 0.1, -0.05]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球018.geometry}
          material={nodes.球018.material}
          position={[0.41, 1.32, -0.21]}
          rotation={[-0.16, 0.1, -0.05]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球019.geometry}
          material={nodes.球019.material}
          position={[0.27, 1.23, -0.3]}
          rotation={[-0.16, 0.1, -0.05]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球020.geometry}
          material={nodes.球020.material}
          position={[0.26, 1.27, -0.3]}
          rotation={[-0.16, 0.1, -0.05]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球021.geometry}
          material={nodes.球021.material}
          position={[0.25, 1.31, 0.16]}
          rotation={[0.32, 0.58, 0.37]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球022.geometry}
          material={nodes.球022.material}
          position={[0.24, 1.33, 0.17]}
          rotation={[0.32, 0.58, 0.37]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球023.geometry}
          material={nodes.球023.material}
          position={[0.38, 1.3, 0.38]}
          rotation={[-0.16, 0.1, -0.05]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球024.geometry}
          material={nodes.球024.material}
          position={[0.38, 1.34, 0.37]}
          rotation={[-0.16, 0.1, -0.05]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球025.geometry}
          material={nodes.球025.material}
          position={[0.43, 1.28, 0.22]}
          rotation={[-0.16, 0.1, -0.05]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球026.geometry}
          material={nodes.球026.material}
          position={[0.43, 1.32, 0.21]}
          rotation={[-0.16, 0.1, -0.05]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球027.geometry}
          material={nodes.球027.material}
          position={[0.51, 1.26, 0.05]}
          rotation={[-3.01, 0.31, -2.66]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球028.geometry}
          material={nodes.球028.material}
          position={[0.52, 1.29, 0.06]}
          rotation={[-3.01, 0.31, -2.66]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球029.geometry}
          material={nodes.球029.material}
          position={[0.58, 1.24, -0.11]}
          rotation={[-0.28, -0.27, -0.14]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球030.geometry}
          material={nodes.球030.material}
          position={[0.58, 1.28, -0.12]}
          rotation={[-0.28, -0.27, -0.14]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球031.geometry}
          material={nodes.球031.material}
          position={[0.55, 1.28, 0.36]}
          rotation={[-0.28, -0.27, -0.14]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球032.geometry}
          material={nodes.球032.material}
          position={[0.55, 1.32, 0.35]}
          rotation={[-0.28, -0.27, -0.14]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球033.geometry}
          material={nodes.球033.material}
          position={[0.62, 1.23, 0.2]}
          rotation={[-0.28, -0.27, -0.14]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球034.geometry}
          material={nodes.球034.material}
          position={[0.63, 1.27, 0.19]}
          rotation={[-0.28, -0.27, -0.14]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球035.geometry}
          material={nodes.球035.material}
          position={[0.46, 1.25, -0.3]}
          rotation={[-0.28, -0.27, -0.14]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球036.geometry}
          material={nodes.球036.material}
          position={[0.46, 1.29, -0.31]}
          rotation={[-0.28, -0.27, -0.14]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球037.geometry}
          material={nodes.球037.material}
          position={[0.53, 1.18, 0.02]}
          rotation={[-0.28, -0.27, -0.14]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球038.geometry}
          material={nodes.球038.material}
          position={[0.53, 1.21, 0.01]}
          rotation={[-0.28, -0.27, -0.14]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球039.geometry}
          material={nodes.球039.material}
          position={[0.02, 1.3, -0.11]}
          rotation={[-0.16, 0.1, -0.05]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球040.geometry}
          material={nodes.球040.material}
          position={[0.02, 1.34, -0.12]}
          rotation={[-0.16, 0.1, -0.05]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球041.geometry}
          material={nodes.球041.material}
          position={[-0.11, 1.3, -0.28]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球042.geometry}
          material={nodes.球042.material}
          position={[-0.11, 1.34, -0.28]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球043.geometry}
          material={nodes.球043.material}
          position={[-0.09, 1.3, 0.04]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球044.geometry}
          material={nodes.球044.material}
          position={[-0.09, 1.34, 0.04]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球045.geometry}
          material={nodes.球045.material}
          position={[-0.2, 1.3, -0.11]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球046.geometry}
          material={nodes.球046.material}
          position={[-0.2, 1.34, -0.12]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球047.geometry}
          material={nodes.球047.material}
          position={[-0.1, 1.3, 0.25]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球048.geometry}
          material={nodes.球048.material}
          position={[-0.1, 1.34, 0.24]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球049.geometry}
          material={nodes.球049.material}
          position={[-0.25, 1.3, 0.35]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球050.geometry}
          material={nodes.球050.material}
          position={[-0.25, 1.34, 0.34]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球051.geometry}
          material={nodes.球051.material}
          position={[-0.26, 1.3, 0.15]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球052.geometry}
          material={nodes.球052.material}
          position={[-0.26, 1.34, 0.15]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球053.geometry}
          material={nodes.球053.material}
          position={[-0.36, 1.3, -0.01]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球054.geometry}
          material={nodes.球054.material}
          position={[-0.36, 1.34, -0.02]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球055.geometry}
          material={nodes.球055.material}
          position={[-0.28, 1.3, -0.3]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球056.geometry}
          material={nodes.球056.material}
          position={[-0.28, 1.34, -0.31]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球057.geometry}
          material={nodes.球057.material}
          position={[-0.46, 1.3, -0.29]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球058.geometry}
          material={nodes.球058.material}
          position={[-0.46, 1.34, -0.3]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球059.geometry}
          material={nodes.球059.material}
          position={[-0.64, 1.3, -0.24]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球060.geometry}
          material={nodes.球060.material}
          position={[-0.64, 1.34, -0.25]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球061.geometry}
          material={nodes.球061.material}
          position={[-0.71, 1.32, -0.1]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球062.geometry}
          material={nodes.球062.material}
          position={[-0.71, 1.35, -0.11]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球063.geometry}
          material={nodes.球063.material}
          position={[-0.54, 1.3, -0.1]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球064.geometry}
          material={nodes.球064.material}
          position={[-0.54, 1.34, -0.11]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球065.geometry}
          material={nodes.球065.material}
          position={[-0.73, 1.3, 0.08]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球066.geometry}
          material={nodes.球066.material}
          position={[-0.73, 1.34, 0.07]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球067.geometry}
          material={nodes.球067.material}
          position={[-0.69, 1.3, 0.25]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球068.geometry}
          material={nodes.球068.material}
          position={[-0.69, 1.34, 0.25]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球069.geometry}
          material={nodes.球069.material}
          position={[-0.56, 1.3, 0.34]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球070.geometry}
          material={nodes.球070.material}
          position={[-0.56, 1.34, 0.33]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球071.geometry}
          material={nodes.球071.material}
          position={[-0.39, 1.3, 0.27]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球072.geometry}
          material={nodes.球072.material}
          position={[-0.39, 1.34, 0.26]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球073.geometry}
          material={nodes.球073.material}
          position={[-0.56, 1.3, 0.16]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球074.geometry}
          material={nodes.球074.material}
          position={[-0.56, 1.34, 0.15]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球075.geometry}
          material={nodes.球075.material}
          position={[0.71, 1.28, 0]}
          rotation={[-0.28, -0.27, -0.14]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球076.geometry}
          material={nodes.球076.material}
          position={[-0.46, 1.37, -0.15]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球077.geometry}
          material={nodes.球077.material}
          position={[-0.46, 1.4, -0.16]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球078.geometry}
          material={nodes.球078.material}
          position={[0.64, 1.28, -0.27]}
          rotation={[-0.28, -0.27, -0.14]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球079.geometry}
          material={nodes.球079.material}
          position={[0.65, 1.32, -0.28]}
          rotation={[-0.28, -0.27, -0.14]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球080.geometry}
          material={nodes.球080.material}
          position={[0.68, 1.32, 0.31]}
          rotation={[-0.28, -0.27, -0.14]}
          scale={[0.08, 0.08, 0.08]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球081.geometry}
          material={nodes.球081.material}
          position={[0.68, 1.35, 0.3]}
          rotation={[-0.28, -0.27, -0.14]}
          scale={[0.03, 0.03, 0.03]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球082.geometry}
          material={nodes.球082.material}
          position={[-0.58, 1.4, 0.01]}
          rotation={[-0.34, 0.01, 1.02]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球083.geometry}
          material={nodes.球083.material}
          position={[-0.61, 1.42, 0.01]}
          rotation={[-0.34, 0.01, 1.02]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球084.geometry}
          material={nodes.球084.material}
          position={[-0.42, 1.41, 0.1]}
          rotation={[-0.41, -0.27, 0.71]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球085.geometry}
          material={nodes.球085.material}
          position={[-0.44, 1.44, 0.09]}
          rotation={[-0.41, -0.27, 0.71]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球086.geometry}
          material={nodes.球086.material}
          position={[-0.32, 1.43, -0.18]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球087.geometry}
          material={nodes.球087.material}
          position={[-0.26, 1.39, 0.01]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球088.geometry}
          material={nodes.球088.material}
          position={[-0.11, 1.33, 0.34]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球089.geometry}
          material={nodes.球089.material}
          position={[0, 1.4, 0.01]}
          rotation={[-0.16, 0.1, -0.05]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球090.geometry}
          material={nodes.球090.material}
          position={[0.16, 1.42, 0.25]}
          rotation={[0.32, 0.58, 0.37]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球091.geometry}
          material={nodes.球091.material}
          position={[0.39, 1.41, 0.1]}
          rotation={[-0.16, 0.1, -0.05]}
          scale={[0.08, 0.08, 0.08]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球092.geometry}
          material={nodes.球092.material}
          position={[0.39, 1.44, 0.1]}
          rotation={[-0.16, 0.1, -0.05]}
          scale={[0.04, 0.04, 0.04]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球093.geometry}
          material={nodes.球093.material}
          position={[0.28, 1.39, -0.06]}
          rotation={[-0.16, 0.1, -0.05]}
          scale={[0.08, 0.08, 0.08]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球094.geometry}
          material={nodes.球094.material}
          position={[0.28, 1.42, -0.07]}
          rotation={[-0.16, 0.1, -0.05]}
          scale={[0.04, 0.04, 0.04]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球095.geometry}
          material={nodes.球095.material}
          position={[0.71, 1.35, 0.16]}
          rotation={[-0.28, -0.27, -0.14]}
          scale={[0.08, 0.08, 0.08]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球096.geometry}
          material={nodes.球096.material}
          position={[0.71, 1.38, 0.16]}
          rotation={[-0.28, -0.27, -0.14]}
          scale={[0.03, 0.03, 0.03]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球097.geometry}
          material={nodes.球097.material}
          position={[0.7, 1.34, -0.14]}
          rotation={[-0.28, -0.27, -0.14]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球098.geometry}
          material={nodes.球098.material}
          position={[0.7, 1.37, -0.15]}
          rotation={[-0.28, -0.27, -0.14]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球099.geometry}
          material={nodes.球099.material}
          position={[0.08, 1.34, -0.19]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球100.geometry}
          material={nodes.球100.material}
          position={[0.08, 1.38, -0.2]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球101.geometry}
          material={nodes.球101.material}
          position={[-0.05, 1.43, -0.14]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.球102.geometry}
          material={nodes.球102.material}
          position={[-0.05, 1.46, -0.15]}
          rotation={[-0.16, -0.04, -0.07]}
          scale={0.04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.shari.geometry}
          material={materials.shari}
          position={[0.02, 1.29, 0.03]}
          rotation={[0, 1.57, 0]}
          scale={[0.45, 0.45, 0.45]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.getavox.geometry}
          material={materials["palette.003"]}
          position={[0.05, 0.33, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.nori_gunkan.geometry}
          material={materials["マテリアル.005"]}
          position={[0.04, 0.9, -0.01]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={1.11}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/images/3d/sushi_ikura.glb");
