/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/images/3d/sushi_ebi2.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" position={[0, -1, 0]}>
        <group name="立方体001" position={[-0.08, 0.82, 0.05]} scale={0.1}>
          <mesh
            name="立方体002_1"
            castShadow
            receiveShadow
            geometry={nodes.立方体002_1.geometry}
            material={materials.Voxel_mat246}
          />
          <mesh
            name="立方体002_2"
            castShadow
            receiveShadow
            geometry={nodes.立方体002_2.geometry}
            material={materials.Voxel_mat247}
          />
          <mesh
            name="立方体002_3"
            castShadow
            receiveShadow
            geometry={nodes.立方体002_3.geometry}
            material={nodes.立方体002_3.material}
          />
          <mesh
            name="立方体002_4"
            castShadow
            receiveShadow
            geometry={nodes.立方体002_4.geometry}
            material={nodes.立方体002_4.material}
          />
          <mesh
            name="立方体002_5"
            castShadow
            receiveShadow
            geometry={nodes.立方体002_5.geometry}
            material={nodes.立方体002_5.material}
          />
          <mesh
            name="立方体002_6"
            castShadow
            receiveShadow
            geometry={nodes.立方体002_6.geometry}
            material={materials.Voxel_mat22}
          />
          <group
            name="アーマチュア"
            position={[7.37, 3.74, 0]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={9.55}
          >
            <primitive object={nodes.Bone} />
          </group>
          <group name="立方体002">
            <skinnedMesh
              name="立方体911"
              geometry={nodes.立方体911.geometry}
              material={nodes.立方体911.material}
              skeleton={nodes.立方体911.skeleton}
            />
            <skinnedMesh
              name="立方体911_1"
              geometry={nodes.立方体911_1.geometry}
              material={nodes.立方体911_1.material}
              skeleton={nodes.立方体911_1.skeleton}
            />
            <skinnedMesh
              name="立方体911_2"
              geometry={nodes.立方体911_2.geometry}
              material={nodes.立方体911_2.material}
              skeleton={nodes.立方体911_2.skeleton}
            />
            <skinnedMesh
              name="立方体911_3"
              geometry={nodes.立方体911_3.geometry}
              material={materials.Voxel_mat21}
              skeleton={nodes.立方体911_3.skeleton}
            />
          </group>
        </group>
        <mesh
          name="getavox"
          castShadow
          receiveShadow
          geometry={nodes.getavox.geometry}
          material={materials["palette.003"]}
          position={[0.05, 0.33, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/images/3d/sushi_ebi2.glb");
