/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/images/3d/sushi_maguro.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" position={[0, -1.3, 0]} scale={9}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.maguro.geometry}
          material={materials.kome}
          position={[-0.01, 0.09, -0.01]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube010_1.geometry}
            material={materials.maguro}
            position={[0.01, 0.09, -0.01]}
            scale={[1.26, 1, 1]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.getavox.geometry}
          material={materials["palette.003"]}
          position={[0, 0.06, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.17}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/images/3d/sushi_maguro.glb");
