/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/images/3d/table.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="table002"
          castShadow
          receiveShadow
          geometry={nodes.table002.geometry}
          material={materials["palette.005"]}
          position={[0, -2, -1.12]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={1.3}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/images/3d/table.glb");
